# Starship config — Gruvbox Dark theme
# Simplified for reliability

format = """
$username\
@$hostname\
 in $directory\
$git_branch\
$git_status\
$line_break\
$character """

[username]
show_always = true
format = "[$user]($style)"
style_user = "bold #ebdbb2"
style_root = "bold #fb4934"

[hostname]
ssh_only = false
format = "[$hostname]($style)"
style = "bold #689d6a"

[directory]
truncation_length = 3
truncation_symbol = "…/"
format = "[$path]($style)"
style = "bold #fabd2f"

[git_branch]
symbol = " "
format = " [$symbol$branch]($style)"
style = "bold #689d6a"

[git_status]
format = "[$all_status$ahead_behind]($style)"
style = "bold #fb4934"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
modified = "!${count}"
staged = "+${count}"
untracked = "?${count}"

[kubernetes]
disabled = false
format = " [$symbol ($context)]($style)"
symbol = "⎈"
style = "bold #689d6a"

[python]
symbol = " "
format = "[$symbol($version)]($style) "
style = "bold #b8bb26"

[nodejs]
symbol = " "
format = "[$symbol($version)]($style) "
style = "bold #b8bb26"

[terraform]
symbol = "󱁢 "
format = "[$symbol($workspace)]($style) "
style = "bold #d3869b"

[character]
success_symbol = "[❯](bold #b8bb26)"
error_symbol = "[❯](bold #fb4934)"
vimcmd_symbol = "[❮](bold #d3869b)"

[time]
disabled = true

[cmd_duration]
min_time = 2000
format = "[ $duration](fg:#fabd2f)"
